services:
  language-library:
    build: .
    image: language-library:latest
    container_name: language-library
    restart: unless-stopped
    ports:
      - "3236:3000"
    environment:
      DATABASE_PATH: /data/app.db
    volumes:
      - ./data:/data
    networks:
      - default
      - web-core_default

networks:
  web-core_default:
    external: true
